/**
 * Curated catalog of current top-tier laptops used by the Laptop Alternative
 * Suggester (src/components/LaptopSuggester.tsx).
 *
 * This is a hand-maintained, offline dataset — no API keys, works in both mock
 * and live modes. Specs and prices are approximate (USD, before tax) and meant
 * for guidance, not exact quotes. Update the list as new models ship.
 *
 * Performance is expressed on a relative 0–100 index (higher = faster) rather
 * than raw benchmark numbers, so the suggester compares machines consistently
 * without implying benchmark-grade precision.
 */

export type UseCase =
  | 'general'
  | 'development'
  | 'creative'
  | 'business'
  | 'gaming';

export type OS = 'macOS' | 'Windows';

export interface Laptop {
  id: string;
  name: string;
  brand: string;
  os: OS;
  cpu: string;
  /** Relative multi-core CPU performance, 0–100 */
  cpuScore: number;
  /** Relative GPU performance, 0–100 */
  gpuScore: number;
  ramGB: number;
  storageGB: number;
  screenInch: number;
  screenNote: string;
  weightKg: number;
  /** Rated battery life in hours (light use) */
  batteryHours: number;
  priceUSD: number;
  bestFor: UseCase[];
  highlights: string[];
}

export const USE_CASE_LABELS: Record<UseCase, string> = {
  general: 'Everyday / general use',
  development: 'Software development',
  creative: 'Creative / video & design',
  business: 'Business / travel',
  gaming: 'Gaming',
};

export const LAPTOP_CATALOG: Laptop[] = [
  {
    id: 'mba-13-m3',
    name: 'MacBook Air 13" (M3)',
    brand: 'Apple',
    os: 'macOS',
    cpu: 'Apple M3',
    cpuScore: 55,
    gpuScore: 42,
    ramGB: 16,
    storageGB: 256,
    screenInch: 13.6,
    screenNote: '13.6" Liquid Retina',
    weightKg: 1.24,
    batteryHours: 18,
    priceUSD: 1099,
    bestFor: ['general', 'business'],
    highlights: ['Fanless & silent', 'All-day battery', 'Very portable'],
  },
  {
    id: 'mba-15-m3',
    name: 'MacBook Air 15" (M3)',
    brand: 'Apple',
    os: 'macOS',
    cpu: 'Apple M3',
    cpuScore: 55,
    gpuScore: 44,
    ramGB: 16,
    storageGB: 256,
    screenInch: 15.3,
    screenNote: '15.3" Liquid Retina',
    weightKg: 1.51,
    batteryHours: 18,
    priceUSD: 1299,
    bestFor: ['general', 'business'],
    highlights: ['Big screen, light body', 'Silent & cool', 'All-day battery'],
  },
  {
    id: 'mbp-14-m4',
    name: 'MacBook Pro 14" (M4)',
    brand: 'Apple',
    os: 'macOS',
    cpu: 'Apple M4',
    cpuScore: 64,
    gpuScore: 55,
    ramGB: 16,
    storageGB: 512,
    screenInch: 14.2,
    screenNote: '14.2" Liquid Retina XDR (120Hz)',
    weightKg: 1.55,
    batteryHours: 22,
    priceUSD: 1599,
    bestFor: ['development', 'creative', 'business'],
    highlights: ['Best-in-class battery', 'Excellent XDR display', 'Great for code & media'],
  },
  {
    id: 'mbp-14-m4-pro',
    name: 'MacBook Pro 14" (M4 Pro)',
    brand: 'Apple',
    os: 'macOS',
    cpu: 'Apple M4 Pro',
    cpuScore: 82,
    gpuScore: 72,
    ramGB: 24,
    storageGB: 512,
    screenInch: 14.2,
    screenNote: '14.2" Liquid Retina XDR (120Hz)',
    weightKg: 1.6,
    batteryHours: 20,
    priceUSD: 1999,
    bestFor: ['development', 'creative'],
    highlights: ['Serious multi-core power', 'Handles heavy builds', 'Quiet under load'],
  },
  {
    id: 'mbp-16-m4-max',
    name: 'MacBook Pro 16" (M4 Max)',
    brand: 'Apple',
    os: 'macOS',
    cpu: 'Apple M4 Max',
    cpuScore: 98,
    gpuScore: 96,
    ramGB: 36,
    storageGB: 1024,
    screenInch: 16.2,
    screenNote: '16.2" Liquid Retina XDR (120Hz)',
    weightKg: 2.14,
    batteryHours: 21,
    priceUSD: 3499,
    bestFor: ['creative', 'development'],
    highlights: ['Workstation-class performance', 'Pro video & 3D ready', 'Huge unified memory'],
  },
  {
    id: 'dell-xps-13',
    name: 'Dell XPS 13 (9350)',
    brand: 'Dell',
    os: 'Windows',
    cpu: 'Intel Core Ultra 7 (Lunar Lake)',
    cpuScore: 58,
    gpuScore: 40,
    ramGB: 16,
    storageGB: 512,
    screenInch: 13.4,
    screenNote: '13.4" OLED touch',
    weightKg: 1.19,
    batteryHours: 16,
    priceUSD: 1299,
    bestFor: ['business', 'general'],
    highlights: ['Premium compact build', 'Sharp OLED', 'Light for travel'],
  },
  {
    id: 'dell-xps-16',
    name: 'Dell XPS 16 (9640)',
    brand: 'Dell',
    os: 'Windows',
    cpu: 'Intel Core Ultra 9 + RTX 4070',
    cpuScore: 78,
    gpuScore: 70,
    ramGB: 16,
    storageGB: 512,
    screenInch: 16.3,
    screenNote: '16.3" OLED 4K',
    weightKg: 2.1,
    batteryHours: 13,
    priceUSD: 1899,
    bestFor: ['creative', 'development'],
    highlights: ['Stunning 4K OLED', 'Discrete RTX GPU', 'Large workspace'],
  },
  {
    id: 'tp-x1-carbon-g12',
    name: 'ThinkPad X1 Carbon Gen 12',
    brand: 'Lenovo',
    os: 'Windows',
    cpu: 'Intel Core Ultra 7',
    cpuScore: 60,
    gpuScore: 38,
    ramGB: 16,
    storageGB: 512,
    screenInch: 14,
    screenNote: '14" IPS / OLED',
    weightKg: 1.09,
    batteryHours: 15,
    priceUSD: 1699,
    bestFor: ['business'],
    highlights: ['Ultra-light 1.09kg', 'Best-in-class keyboard', 'Business-grade durability'],
  },
  {
    id: 'legion-pro-7i',
    name: 'Legion Pro 7i (RTX 4080)',
    brand: 'Lenovo',
    os: 'Windows',
    cpu: 'Intel Core i9 + RTX 4080',
    cpuScore: 85,
    gpuScore: 92,
    ramGB: 32,
    storageGB: 1024,
    screenInch: 16,
    screenNote: '16" 240Hz QHD+',
    weightKg: 2.8,
    batteryHours: 6,
    priceUSD: 2499,
    bestFor: ['gaming', 'creative'],
    highlights: ['Top-tier gaming GPU', '240Hz display', 'Strong cooling'],
  },
  {
    id: 'rog-g14-2024',
    name: 'ROG Zephyrus G14 (2024)',
    brand: 'ASUS',
    os: 'Windows',
    cpu: 'Ryzen 9 + RTX 4070',
    cpuScore: 74,
    gpuScore: 78,
    ramGB: 32,
    storageGB: 1024,
    screenInch: 14,
    screenNote: '14" OLED 120Hz',
    weightKg: 1.5,
    batteryHours: 10,
    priceUSD: 1999,
    bestFor: ['gaming', 'creative'],
    highlights: ['Gaming power in 1.5kg', 'Gorgeous OLED', 'Surprisingly portable'],
  },
  {
    id: 'zenbook-14-oled',
    name: 'Zenbook 14 OLED',
    brand: 'ASUS',
    os: 'Windows',
    cpu: 'Intel Core Ultra 7',
    cpuScore: 60,
    gpuScore: 42,
    ramGB: 16,
    storageGB: 1024,
    screenInch: 14,
    screenNote: '14" OLED',
    weightKg: 1.2,
    batteryHours: 17,
    priceUSD: 1099,
    bestFor: ['general', 'business'],
    highlights: ['Great value OLED', '1TB storage included', 'Light & long battery'],
  },
  {
    id: 'hp-spectre-x360-14',
    name: 'HP Spectre x360 14',
    brand: 'HP',
    os: 'Windows',
    cpu: 'Intel Core Ultra 7',
    cpuScore: 58,
    gpuScore: 40,
    ramGB: 16,
    storageGB: 1024,
    screenInch: 14,
    screenNote: '14" OLED 2-in-1 touch',
    weightKg: 1.44,
    batteryHours: 14,
    priceUSD: 1450,
    bestFor: ['business', 'general'],
    highlights: ['Convertible 2-in-1', 'Pen support', 'Premium finish'],
  },
  {
    id: 'framework-13-amd',
    name: 'Framework Laptop 13 (AMD)',
    brand: 'Framework',
    os: 'Windows',
    cpu: 'Ryzen 7 7840U',
    cpuScore: 62,
    gpuScore: 45,
    ramGB: 16,
    storageGB: 512,
    screenInch: 13.5,
    screenNote: '13.5" 3:2 matte',
    weightKg: 1.3,
    batteryHours: 12,
    priceUSD: 1399,
    bestFor: ['development', 'general'],
    highlights: ['User-repairable & upgradeable', 'Swappable ports', 'Linux-friendly'],
  },
  {
    id: 'razer-blade-16',
    name: 'Razer Blade 16 (RTX 4090)',
    brand: 'Razer',
    os: 'Windows',
    cpu: 'Intel Core i9 + RTX 4090',
    cpuScore: 88,
    gpuScore: 98,
    ramGB: 32,
    storageGB: 1024,
    screenInch: 16,
    screenNote: '16" OLED dual-mode',
    weightKg: 2.45,
    batteryHours: 7,
    priceUSD: 2999,
    bestFor: ['gaming', 'creative'],
    highlights: ['Fastest mobile GPU', 'CNC aluminium build', 'Creator + gamer crossover'],
  },
  {
    id: 'surface-laptop-7',
    name: 'Surface Laptop 7 (X Elite)',
    brand: 'Microsoft',
    os: 'Windows',
    cpu: 'Snapdragon X Elite',
    cpuScore: 64,
    gpuScore: 44,
    ramGB: 16,
    storageGB: 512,
    screenInch: 13.8,
    screenNote: '13.8" PixelSense touch',
    weightKg: 1.34,
    batteryHours: 20,
    priceUSD: 1299,
    bestFor: ['business', 'general'],
    highlights: ['Outstanding battery (ARM)', 'Silent & cool', 'Touch display'],
  },
  {
    id: 'acer-swift-go-14',
    name: 'Acer Swift Go 14',
    brand: 'Acer',
    os: 'Windows',
    cpu: 'Intel Core Ultra 5',
    cpuScore: 50,
    gpuScore: 32,
    ramGB: 16,
    storageGB: 512,
    screenInch: 14,
    screenNote: '14" OLED',
    weightKg: 1.32,
    batteryHours: 12,
    priceUSD: 799,
    bestFor: ['general'],
    highlights: ['OLED on a budget', 'Solid everyday performance', 'Great price'],
  },
  {
    id: 'lg-gram-16',
    name: 'LG gram 16',
    brand: 'LG',
    os: 'Windows',
    cpu: 'Intel Core Ultra 7',
    cpuScore: 58,
    gpuScore: 38,
    ramGB: 16,
    storageGB: 512,
    screenInch: 16,
    screenNote: '16" IPS',
    weightKg: 1.19,
    batteryHours: 16,
    priceUSD: 1499,
    bestFor: ['business', 'general'],
    highlights: ['16" screen at just 1.19kg', 'Long battery', 'Easy to carry'],
  },
];
